# Generated by Django 4.0.3 on 2022-03-16 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('middleware_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='maxcount',
            name='count',
            field=models.IntegerField(default=3),
        ),
    ]
