# Generated by Django 4.0.3 on 2022-03-16 12:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('middleware_app', '0002_alter_maxcount_count'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='maxcount',
            name='url',
        ),
    ]
