# Generated by Django 4.0.3 on 2022-03-16 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('middleware_app', '0003_remove_maxcount_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='maxcount',
            name='url',
            field=models.CharField(default=0, max_length=200, unique=True),
            preserve_default=False,
        ),
    ]
